server.port=8080

spring.datasource.url=jdbc:h2:mem:flowable;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

# Flowable will auto-create tables
flowable.database-schema-update=true
logging.level.org.flowable.rest=DEBUG
logging.level.org.flowable.app=DEBUG


logging.level.org.springframework.boot.autoconfigure=DEBUG

flowable.rest.app.base-url=/process-api

spring.kafka.bootstrap-servers=10.165.187.17:9092

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-serializer=org.apache.kafka.common.serialization.StringSerializer


flowable.eventregistry.enabled=true
flowable.eventregistry.kafka.enabled=false
flowable.async-executor-activate=false
flowable.history-level=full